### ISSUE TITLE
Can I search for replies to tweets based on their ID?

### ISSUE THREAD

**Issue by 809388027** [Rishikant181/Twitter-Analysis-Backend#27]
I want to synchronize the replies under the tweet as well (even the first few dozen)

**Comment by Rishikant181** [comment]
This is not the project you are looking for.

You might want to check out https://github.com/Rishikant181/Rettiwt-API

Even then, fetching replies functionality is disabled for now since it gives inconsistent results.

**Comment by 809388027** [comment]
Okay, thank you
